version: '3'

services:
  fastfeast:
    build: .
    container_name: FastFeast
    #command: bash -c ".celery -A mysite worker --loglevel=info && python manage.py runserver 0.0.0.0:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    environment:
      - CELERY_BROKER= redis://redis:6379/0
    depends_on:
      - pgdb
      - redis

  pgdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    ports:
      - "5433:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A mysite worker -l INFO
    volumes:
      - ./:/src
    depends_on:
      - fastfeast
      - redis

volumes:
  pgdbdata: