version: '3'

services:
  fastfeast:
    build: .
    container_name: FastFeast
#    command: bash -c "./manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    ports:
      - "5433:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: